apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-familie-ba-sak-opphoer-barnetrygd
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168 # -1 means unlimited
  acl:
    - team: teamfamilie
      application: familie-ba-sak #owner
      access: write   # readwrite
    - team: bidrag
      application: bidrag-automatisk-jobb-q1 #consumer
      access: read
    - team: bidrag
      application: bidrag-automatisk-jobb-q2 #consumer
      access: read
    - team: teamfamilie
      application: familie-baks-kafka-manager
      access: read