apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{image}}
  port: 8089
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvfamilie-ba-sak
        mountPath: /var/run/secrets/srvfamilie-ba-sak
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "1"
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ba-sak.dev-fss-pub.nais.io # Deprecated - erstattes av dev.adeo.no
    - https://familie-ba-sak.dev.adeo.no
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: SRVUSER_BA_SAK_SECRET
      value: /var/run/secrets/srvfamilie-ba-sak/password
