/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://packages.confluent.io/maven/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/navikt/familie-felles")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.jetty)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.org.flywaydb.flyway.core)
    api(libs.org.springframework.kafka.spring.kafka)
    api(libs.com.neovisionaries.nv.i18n)
    api(libs.com.papertrailapp.logback.syslog4j)
    api(libs.org.postgresql.postgresql)
    api(libs.io.getunleash.unleash.client.java)
    api(libs.org.yaml.snakeyaml)
    api(libs.org.eclipse.jetty.jetty.server)
    api(libs.org.apache.maven.maven.model)
    api(libs.io.sentry.sentry.spring.boot.starter.jakarta)
    api(libs.io.sentry.sentry.logback)
    api(libs.org.apache.avro.avro)
    api(libs.io.confluent.kafka.avro.serializer)
    api(libs.org.springdoc.springdoc.openapi.starter.common)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    api(libs.no.nav.security.token.client.spring)
    api(libs.no.nav.security.token.client.core)
    api(libs.nav.foedselsnummer.core)
    api(libs.no.nav.familie.felles.sikkerhet)
    api(libs.no.nav.familie.prosessering.core)
    api(libs.no.nav.familie.felles.log)
    api(libs.no.nav.familie.felles.leader)
    api(libs.no.nav.familie.felles.unleash)
    api(libs.no.nav.familie.felles.http.client)
    api(libs.no.nav.familie.felles.modell)
    api(libs.no.nav.familie.felles.util)
    api(libs.no.nav.familie.felles.valutakurs.klient)
    api(libs.no.nav.familie.felles.metrikker)
    api(libs.no.nav.familie.kontrakter.felles)
    api(libs.no.nav.familie.kontrakter.barnetrygd)
    api(libs.no.nav.familie.eksterne.kontrakter.bisys)
    api(libs.no.nav.familie.eksterne.kontrakter.stonadsstatistikk)
    api(libs.no.nav.familie.eksterne.kontrakter.saksstatistikk)
    api(libs.no.nav.familie.felles.familie.utbetalingsgenerator)
    api(libs.org.springframework.retry.spring.retry)
    api(libs.com.github.jsqlparser.jsqlparser)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    runtimeOnly(libs.org.flywaydb.flyway.database.postgresql)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.testcontainers.postgresql)
    testImplementation(libs.no.nav.security.token.validation.spring.test)
    testImplementation(libs.no.nav.security.mock.oauth2.server)
    testImplementation(libs.nav.foedselsnummer.testutils)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.io.mockk.mockk.jvm)
    testImplementation(libs.org.wiremock.wiremock.standalone)
    testImplementation(libs.com.worldturner.medeia.medeia.validator.jackson)
    testImplementation(libs.io.cucumber.cucumber.java)
    testImplementation(libs.io.cucumber.cucumber.junit.platform.engine)
    testImplementation(libs.org.junit.platform.junit.platform.suite)
}

group = "no.nav.familie.ba.sak"
version = "1-SNAPSHOT"
description = "familie-ba-sak"
java.sourceCompatibility = JavaVersion.VERSION_1_8

configurations.all {
    exclude(mapOf("group" to "org.junit.*"))
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
