apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nais.io/run-as-group: "65532"
    nais.io/run-as-user: "65532"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: '1'
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

spec:
  envFrom:
    - secret: familie-ba-sak
    - secret: familie-ba-sak-unleash-api-token
  image: {{image}}
  port: 8089
  leaderElection: true
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_15 # Read nais doc and https://github.com/navikt/familie/blob/master/doc/Google%20cloud/oppgrader-database.md on how to upgrade
        tier: db-custom-4-3840
        name: familie-ba-sak
        autoBackupHour: 2
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: familie-ba-sak
            envVarPrefix: DB
        flags:
          - name: cloudsql.enable_pgaudit
            value: "on"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"  # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 tilgang til prosessering
          - id: "199c2b39-e535-4ae8-ac59-8ccbee7991ae"  # VEILEDER_ROLLE
          - id: "847e3d72-9dc1-41c3-80ff-f5d4acdd5d46"  # SAKSBEHANDLER_ROLLE
          - id: "7a271f87-39fb-468b-a9ee-6cf3c070f548"  # BESLUTTER_ROLLE
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0"  # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b"  # 0000-GA-Fortrolig_Adresse
          - id: "024bfb25-ead3-4c04-bbe1-1db3d3362188"  # team-baks-forvaltning
      replyURLs:
        - "https://familie-ba-sak.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak-frontend
          cluster: prod-gcp
        - application: familie-baks-mottak
          cluster: prod-gcp
        - application: familie-prosessering
          cluster: prod-gcp
        - application: familie-klage
          cluster: prod-gcp
        - application: bidrag-grunnlag-feature
          namespace: bidrag
          cluster: prod-gcp
        - application: bidrag-grunnlag
          namespace: bidrag
          cluster: prod-gcp
        - application: omsorgsopptjening-start-innlesning
          namespace: pensjonopptjening
          cluster: prod-gcp
        - application: familie-ba-minside-frontend
          namespace: teamfamilie
          cluster: prod-gcp
    outbound:
      rules:
        - application: familie-brev
          cluster: prod-gcp
        - application: familie-integrasjoner
          cluster: prod-fss
        - application: familie-ba-infotrygd-feed
          cluster: prod-fss
        - application: familie-ba-infotrygd
          cluster: prod-fss
        - application: familie-ef-sak
          cluster: prod-gcp
        - application: familie-tilbake
          cluster: prod-gcp
        - application: tilbakekreving-backend
          namespace: tilbake
          cluster: prod-gcp
        - application: familie-oppdrag
          cluster: prod-fss
        - application: familie-klage
          cluster: prod-gcp
        - application: logging
          namespace: nais-system
      external:
        - host: xsrv1mh6.api.sanity.io
        - host: unleash.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: familie-ba-infotrygd.prod-fss-pub.nais.io
        - host: familie-ba-infotrygd-feed.prod-fss-pub.nais.io
        - host: sdw-wsrest.ecb.europa.eu
        - host: sentry.gc.nav.no
        - host: data-api.ecb.europa.eu
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
        # Sanity IPs https://www.sanity.io/docs/api-cdn#5fa01dfe1285 (Fjernes når feilen er rettet av platform teamet https://nav-it.slack.com/archives/C5KUST8N6/p1719994144462539)
        - ipv4: 35.241.31.122
        - ipv4: 35.190.70.79
        - ipv4: 35.186.208.30
        - ipv4: 34.102.229.159
        - ipv4: 34.102.211.197
        - ipv4: 34.102.168.221
        - ipv4: 34.102.220.13
        - ipv4: 34.102.190.179
        - ipv4: 34.102.233.224
        - ipv4: 34.117.95.95
        - ipv4: 34.160.140.40
        - ipv4: 34.111.181.219
        - ipv4: 34.111.150.233
        - ipv4: 34.107.216.191
        - ipv4: 34.102.242.91
        - ipv4: 35.201.85.63
        - ipv4: 35.190.90.94
        - ipv4: 34.117.92.90
        - ipv4: 34.149.250.58
        - ipv4: 34.160.166.218
        - ipv4: 34.160.171.86
        - ipv4: 34.36.58.112
        - ipv4: 34.117.0.159
        - ipv4: 34.117.101.53
        - ipv4: 34.49.170.196
        - ipv4: 34.49.206.188
        - ipv4: 35.201.69.243
        - ipv4: 34.149.200.141
        - ipv4: 34.98.114.57
        - ipv4: 34.36.101.172
        - ipv4: 34.49.15.205
        - ipv4: 34.117.26.18
        - ipv4: 34.95.108.139
        - ipv4: 34.49.19.79
        - ipv4: 34.49.99.193
        - ipv4: 34.110.228.169
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 4096Mi
      cpu: 886m
  ingresses:
    - https://familie-ba-sak.intern.nav.no
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  kafka:
    pool: nav-prod
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
