no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${BA_SAK_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      familie-integrasjoner-onbehalfof:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-oppdrag-clientcredentials:
        resource-url: ${FAMILIE_OPPDRAG_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_OPPDRAG_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-feed-clientcredentials:
        resource-url: ${FAMILIE_BA_INFOTRYGD_FEED_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_BA_INFOTRYGD_FEED_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-barnetrygd-clientcredentials:
        resource-url: ${FAMILIE_BA_INFOTRYGD_BARNETRYGD_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_BA_INFOTRYGD_BARNETRYGD_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic


ACCEPTED_CLIENTS: ${BA_SAK_FRONTEND_CLIENT_ID}, ${BA_MOTTAK_CLIENT_ID}, ${FAMILIE_PROSESSERING_CLIENT_ID}

logging:
  config: "classpath:logback-test.xml"
  level:
    root: INFO

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://dummy/api/
    cluster: localhost
    applicationName: familie-ba-sak

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false

FAMILIE_INTEGRASJONER_API_URL: http://localhost:8085/api
FAMILIE_BA_INFOTRYGD_FEED_API_URL: http://localhost:8092/api
FAMILIE_BA_INFOTRYGD_BARNETRYGD_API_URL: http://localhost:8093
STS_URL: "dummy"
PDL_URL: "dummy"
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw

#Unleash
UNLEASH_API_URL: http://localhost
