

logging:
  config: "classpath:logback-test.xml"
  level:
    root: INFO
sentry.environment: local
sentry.logging.enabled: false

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://dummy/api/
    cluster: localhost
    applicationName: familie-ba-sak
  kafka:
    producer:
      enabled: false

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: http://localhost:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS

FAMILIE_INTEGRASJONER_SCOPE: "dummy"

FAMILIE_INTEGRASJONER_API_URL: http://localhost:8085/api
FAMILIE_BA_INFOTRYGD_FEED_API_URL: http://localhost:8092/api
FAMILIE_BA_INFOTRYGD_API_URL: http://localhost:8093
FAMILIE_TILBAKE_API_URL: http://localhost:8030/api
FAMILIE_OPPDRAG_API_URL: http://localhost:8087/api
PDL_URL: "dummy"
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw

retry.backoff.delay: 5
DEPLOY_ENV: dev
