no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${BA_SAK_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      familie-integrasjoner-onbehalfof:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-onbehalfof:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-clientcredentials:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-oppdrag-clientcredentials:
        resource-url: ${FAMILIE_OPPDRAG_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_OPPDRAG_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-onbehalfof:
        resource-url: ${FAMILIE_BA_INFOTRYGD_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_BA_INFOTRYGD_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-feed-clientcredentials:
        resource-url: ${FAMILIE_BA_INFOTRYGD_FEED_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_BA_INFOTRYGD_FEED_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-clientcredentials:
        resource-url: ${FAMILIE_BA_INFOTRYGD_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_BA_INFOTRYGD_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-oppdrag-onbehalfof:
        resource-url: ${FAMILIE_OPPDRAG_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_OPPDRAG_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-tilbake-onbehalfof:
        resource-url: ${FAMILIE_TILBAKE_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_TILBAKE_API_URL_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-tilbake-clientcredentials:
        resource-url: ${FAMILIE_TILBAKE_API_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_TILBAKE_API_URL_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic


logging:
  config: "classpath:logback-test.xml"
  level:
    root: INFO
sentry.environment: local
sentry.logging.enabled: false

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://dummy/api/
    cluster: localhost
    applicationName: familie-ba-sak
  kafka:
    producer:
      enabled: false

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: http://localhost:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS

FAMILIE_INTEGRASJONER_SCOPE: "dummy"

FAMILIE_INTEGRASJONER_API_URL: http://localhost:8085/api
FAMILIE_BA_INFOTRYGD_FEED_API_URL: http://localhost:8092/api
FAMILIE_BA_INFOTRYGD_API_URL: http://localhost:8093
FAMILIE_TILBAKE_API_URL: http://localhost:8030/api
FAMILIE_OPPDRAG_API_URL: http://localhost:8087/api
FAMILIE_STATISTIKK_URL: dummy
PDL_URL: "dummy"
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw

retry.backoff.delay: 5
DEPLOY_ENV: dev
