apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-familie-ba-sak-stoenadsstatistikk
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-prod
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 1440 # -1 means unlimited
  acl:
    - team: teamfamilie
      application: familie-ba-sak #owner
      access: write   # readwrite
    - team: teamfamilie
      application: familie-ba-mottak #testing
      access: read   # testing
    - team: dv-familie
      application: dvh-fambt-konsumer #consumer
      access: read