apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-barnetrygd-vedtak-v1
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1 # -1 means unlimited
  acl:
    - team: teamfamilie
      application: familie-ba-sak #owner
      access: write   # readwrite
    - team: teamfamilie
      application: familie-ba-statistikk
      access: read
    - team: teamfamilie
      application: aivia-barnetrygd-vedtak
      access: write
    - team: teamfamilie
      application: familie-ba-kafka-manager
      access: read
