CREATE TABLE SKYGGESAK
(
    ID               BIGINT                              NOT NULL PRIMARY KEY,
    FK_FAGSAK_ID     BIGINT                              NOT NULL,
    SENDT_TID   TIMESTAMP(3)
);

CREATE SEQUENCE SKYGGESAK_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;