ALTER TABLE IF EXISTS EKSTERN_BEHANDLING_RELASJON RENAME COLUMN intern_behandling_id TO fk_behandling_id;
ALTER TABLE IF EXISTS EKSTERN_BEHANDLING_RELASJON RENAME COLUMN opprettet_tidspunkt TO opprettet_tid;

ALTER TABLE IF EXISTS EKSTERN_BEHANDLING_RELASJON ALTER COLUMN ekstern_behandling_id TYPE VARCHAR;
ALTER TABLE IF EXISTS EKSTERN_BEHANDLING_RELASJON ALTER COLUMN ekstern_behandling_fagsystem TYPE VARCHAR;