CREATE TABLE IF NOT EXISTS FINNMARKSTILLEGG_KJOERING
(
    ID           BIGINT                                          NOT NULL PRIMARY KEY,
    FK_FAGSAK_ID BIGINT REFERENCES FAGSAK (ID) ON DELETE CASCADE NOT NULL,
    START_TID    TIMESTAMP(3) DEFAULT LOCALTIMESTAMP             NOT NULL,
    FERDIG_TID   TIMESTAMP(3)
);

CREATE SEQUENCE FINNMARKSTILLEGG_KJOERING_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX finnmarkstillegg_kjoering_fagsak_id_idx ON finnmarkstillegg_kjoering (fk_fagsak_id);