CREATE TABLE IF NOT EXISTS SVALBARDSTILLEGG_KJOERING
(
    ID           BIGINT                                          NOT NULL PRIMARY KEY,
    FK_FAGSAK_ID BIGINT REFERENCES FAGSAK (ID) ON DELETE CASCADE NOT NULL
);

CREATE SEQUENCE SVALBARDSTILLEGG_KJOERING_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX svalbardstillegg_kjoering_fagsak_id_idx ON svalbardstillegg_kjoering (fk_fagsak_id);