-- Ny koblingstabell mot AKTOER i stedet for PO_PERSON
CREATE TABLE IF NOT EXISTS AKTOER_TIL_ENDRET_UTBETALING_ANDEL
(
    FK_ENDRET_UTBETALING_ANDEL_ID BIGINT  NOT NULL,
    FK_AKTOER_ID                  VARCHAR NOT NULL,

    PRIMARY KEY (FK_ENDRET_UTBETALING_ANDEL_ID, FK_AKTOER_ID),
    CONSTRAINT FK_ENDRET_UTBETALING_ANDEL FOREIGN KEY (FK_ENDRET_UTBETALING_ANDEL_ID)
        REFERENCES ENDRET_UTBETALING_ANDEL (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AKTOER FOREIGN KEY (FK_AKTOER_ID)
        REFERENCES AKTOER (AKTOER_ID) ON UPDATE CASCADE
);

-- Migrer data via PO_PERSON sin aktør-referanse
INSERT INTO AKTOER_TIL_ENDRET_UTBETALING_ANDEL (FK_ENDRET_UTBETALING_ANDEL_ID, FK_AKTOER_ID)
SELECT DISTINCT PERSON_TIL_ENDRET_UTBETALING_ANDEL.FK_ENDRET_UTBETALING_ANDEL_ID, PO_PERSON.FK_AKTOER_ID
FROM PERSON_TIL_ENDRET_UTBETALING_ANDEL
    JOIN PO_PERSON ON PO_PERSON.ID = PERSON_TIL_ENDRET_UTBETALING_ANDEL.FK_PERSON_ID;

DROP TABLE IF EXISTS PERSON_TIL_ENDRET_UTBETALING_ANDEL;
