INSERT INTO FAGSAK_PERSON (ID, FK_FAGSAK_ID, IDENT, OPPRETTET_AV, OPPRETTET_TID)
SELECT nextval('FAGSAK_PERSON_SEQ'), ID, PERSON_IDENT, OPPRETTET_AV, OPPRETTET_TID FROM FAGSAK;

--ALTER TABLE FAGSAK DROP COLUMN PERSON_IDENT;