ALTER TABLE JOURNALPOST
    ADD COLUMN OPPRETTET_TID TIMESTAMP(3) DEFAULT localtimestamp;

UPDATE JOURNALPOST
SET OPPRETTET_TID = '2020-06-24 00:00:00-00';

ALTER TABLE behandling
    DROP COLUMN journalpost_id;
