CREATE TABLE OPPLYSNINGSPLIKT
(
    ID                      BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID        BIGINT REFERENCES behandling (id)   NOT NULL,
    OPPLYSNINGSPLIKT_STATUS TEXT,
    BEGRUNNELSE             TEXT,
    OPPRETTET_AV            VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT localtimestamp NOT NULL
);

CREATE SEQUENCE OPPLYSNINGSPLIKT_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;