name: Pull request
on:
  workflow_dispatch:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ktlint:
    name: Ktlint
    permissions:
      contents: read
    uses: navikt/familie-baks-gha-workflows/.github/workflows/ktlint.yaml@pull-request # ratchet:exclude
    secrets: inherit

  unit-test:
    name: Unit test
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/pull-request-maven.yaml@pull-request # ratchet:exclude
    with:
      profile: 'enhetstest'
      with-coverage: ${{ github.event_name != 'merge_group' && true || false }}
      coverage-artifact-name: 'enhetstest'
      coverage-artifact-path: 'target/coverage/enhetstest.xml'
    secrets: inherit

  integration-test:
    name: Integration test
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/pull-request-maven.yaml@pull-request # ratchet:exclude
    with:
      profile: 'integrasjonstest'
      with-coverage: ${{ github.event_name != 'merge_group' && true || false }}
      coverage-artifact-name: 'integrasjonstest'
      coverage-artifact-path: 'target/coverage/integrasjonstest.xml'
    secrets: inherit

  verdikjedetest-feature-toggle-off:
    name: Verdikjedetester toggle off
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/pull-request-maven.yaml@pull-request # ratchet:exclude
    with:
      profile: 'verdikjedetest'
      maven-custom-args: '-DargLine="-DmockFeatureToggleAnswer=false"'
    secrets: inherit

  verdikjedetest-feature-toggle-on:
    name: Verdikjedetester toggle on
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/pull-request-maven.yaml@pull-request # ratchet:exclude
    with:
      profile: 'verdikjedetest'
      maven-custom-args: '-DargLine="-DmockFeatureToggleAnswer=true"'
    secrets: inherit

  sonar:
    if: github.actor != 'dependabot[bot]' && github.event_name != 'merge_group'
    name: Sonar
    needs: [ unit-test, integration-test ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/sonar.yaml@pull-request # ratchet:exclude
    with:
      unit-test-artifact-name: 'enhetstest'
      unit-test-artifact-path: 'coverage/enhetstest'
      integration-test-artifact-name: 'integrasjonstest'
      integration-test-artifact-path: 'coverage/integrasjonstest'
    secrets: inherit

