name: KRISE-eksisterende-image-RETT-I-PROD
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for imaget som skal ut. Kun tag, ikkje fullt namn'
        required: true
        type: string
env:
  IMAGE: ghcr.io/navikt/familie-ba-sak
jobs:
  deploy-to-prod:
    name: Deploy eksisterende image til prod-gcp (MÅ KUN BRUKES VED KRISE)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/app-prod.yaml
          VAR: image=${{ env.IMAGE }}:${{ inputs.tag }},GITHUB_BRANCH=${{ github.ref_name }},GITHUB_SHA:${{ github.sha }}

  loggfeil:
    name: Send logg til slack ved feil
    runs-on: ubuntu-latest
    needs: [deploy-to-prod]
    if: failure()
    steps:
      - name: Send logg til slack ved feil
        run: |
          curl -X POST --data "{\"text\": \"Deploy av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
