name: Build-E2E-Push
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

env:
  IMAGE: ghcr.io/navikt/familie-ba-sak:${{ github.sha }}
jobs:
  build-jar-docker:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Bygg med maven + sonar
        env:
          SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ${{ github.event_name == 'pull_request' }}
          then
            mvn -B --no-transfer-progress package verify sonar:sonar --settings .m2/maven-settings.xml --file pom.xml
          else
            mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml
          fi
      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $IMAGE

  run-e2e:
    name: Kjør e2e tester
    runs-on: ubuntu-latest
    needs: build-jar-docker
    steps:
      - uses: navikt/github-app-token-generator@v1.1
        id: get-token
        with:
          private-key: ${{ secrets.REPO_CLONER_PRIVATE_KEY }}
          app-id: ${{ secrets.REPO_CLONER_APP_ID }}
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PUSH_PACKAGE_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout e2e tests
        if: "!contains(github.event.head_commit.message, 'e2e skip')"
        uses: actions/checkout@v2
        with:
          ref: "master"
          repository: navikt/familie-ba-e2e
          token: ${{ steps.get-token.outputs.token }}
          path: ba-e2e
      - name: Setter riktig ba-sak versjon i e2e tester
        if: "!contains(github.event.head_commit.message, 'e2e skip')"
        run: sed -i 's/familie-ba-sak:latest/familie-ba-sak:'$GITHUB_SHA'/g' ba-e2e/e2e/docker-compose.yml
      - name: Start alle apper (e2e)
        env:
          INTEGRASJONER_CLIENT_ID: ${{ secrets.INTEGRASJONER_CLIENT_ID }}
          INTEGRASJONER_CLIENT_SECRET: ${{ secrets.INTEGRASJONER_CLIENT_SECRET }}
          INTEGRASJONER_INFOTRYGD_KS_SCOPE: ${{ secrets.INTEGRASJONER_INFOTRYGD_KS_SCOPE }}
          INTEGRASJONER_AAD_GRAPH_SCOPE: ${{ secrets.INTEGRASJONER_AAD_GRAPH_SCOPE }}
          SAK_CLIENT_ID: ${{ secrets.SAK_CLIENT_ID }}
          SAK_CLIENT_SECRET: ${{ secrets.SAK_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SAK_FRONTEND_CLIENT_ID: ${{ secrets.SAK_FRONTEND_CLIENT_ID }}
          SAK_FRONTEND_CLIENT_SECRET: ${{ secrets.SAK_FRONTEND_CLIENT_SECRET }}
          OPPDRAG_CLIENT_ID: ${{ secrets.OPPDRAG_CLIENT_ID }}
          INTEGRASJONER_SCOPE: ${{ secrets.INTEGRASJONER_SCOPE }}
          OPPDRAG_SCOPE: ${{ secrets.OPPDRAG_SCOPE }}
          BA_SAK_SCOPE: ${{ secrets.BA_SAK_SCOPE }}
          MOTTAK_CLIENT_ID: ${{ secrets.MOTTAK_CLIENT_ID }}
          MOTTAK_CLIENT_SECRET: ${{ secrets.MOTTAK_CLIENT_SECRET }}
          SRVUSER_BA_SAK_SECRET: ${{ secrets.SRVUSER_BA_SAK_SECRET }}
          FAMILIE_TILBAKE_API_URL_SCOPE: ${{ secrets.FAMILIE_TILBAKE_API_URL_SCOPE }}
          TILBAKE_CLIENT_ID: ${{ secrets.TILBAKE_CLIENT_ID }}
          AZURE_APP_CLIENT_ID: ${{ secrets.AZURE_APP_CLIENT_ID }}
        if: "!contains(github.event.head_commit.message, 'e2e skip')"
        run: cd ba-e2e/e2e; ./e2e.sh
      - name: Kjør tester (e2e)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "!contains(github.event.head_commit.message, 'e2e skip')"
        run: cd ba-e2e/autotest; mvn -B --no-transfer-progress --settings .m2/maven-settings.xml -Dtest="**" test
      - name: Samle Docker-logs ved feil
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Laste opp logs til GitHub
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: docker-logs-${{ github.run_number }}.tgz
          path: ./logs.tgz
          retention-days: 2