name: KRISE-RETT-I-PROD
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-ba-sak:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ba-sak:latest
jobs:
  deploy-to-prod:
    name: Bygg app/image, push til github, deploy til prod-gcp (MÅ KUN BRUKES VED KRISE)
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Bygg med maven
        env:
          SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -Dmaven.test.skip=true -e -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          tag: latest
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/app-prod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}