name: Deploy proxy i dev-fss
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-ba-sak:proxy:${{ github.sha }}
jobs:
  deploy-proxy-to-dev-fss:
    name: Bygg proxy, push til github, deploy til dev-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bygg Docker image
        run: |
          docker build -t ${IMAGE} .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $IMAGE
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: dev-fss
          RESOURCE: .deploy/ba-sak-proxy/nais.yaml