name: Manual deploy with image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prod
      image:
        required: true
        type: string
        description: 'Image tag to deploy (ex: 2025.02.14-14.40-70a41ds)'
jobs:
  deploy-with-existing-image:
    name: Deploy with existing image
    if: inputs.image != ''
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy-with-tag.yaml@main # ratchet:exclude
    with:
      image-tag: ${{ inputs.image }}
      cluster: ${{ inputs.environment }}-gcp
      resource: .nais/app-${{ inputs.environment }}.yaml
    secrets: inherit
  notify-audit:
    name: Notify if audited deploy
    if: github.ref != 'refs/heads/main' && inputs.environment == 'prod'
    permissions: {}
    needs: deploy-with-existing-image
    uses: navikt/familie-baks-gha-workflows/.github/workflows/notify-audited-deploy.yaml@main # ratchet:exclude
    secrets:
      BAKS_AUDIT_ALERTS_SLACK_WEBHOOK: ${{ secrets.BAKS_AUDIT_ALERTS_SLACK_WEBHOOK }}
