name: Deploy kafka topics

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy bisys_opphoer_av_barnetrygd_topic til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka/dev/bisys_opphoer_av_barnetrygd.yaml
      - name: Deploy bisys_opphoer_av_barnetrygd_topic til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka/prod/bisys_opphoer_av_barnetrygd.yaml
      - name: Deploy dvh_vedtak_topic til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka/dev/dvh_vedtak_topic.yaml
      - name: Deploy dvh_vedtak_topic til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka/prod/dvh_vedtak_topic.yaml
      - name: Deploy dvh_saksstatistikk_sak_v1_topic til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka/dev/dvh_saksstatistikk_sak_v1_topic.yaml
      - name: Deploy dvh_saksstatistikk_sak_v1_topic til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka/prod/dvh_saksstatistikk_sak_v1_topic.yaml
      - name: Deploy dvh_sakstatistikk_behandling_v1_topic til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka/dev/dvh_sakstatistikk_behandling_v1_topic.yaml
      - name: Deploy dvh_sakstatistikk_behandling_v1_topic til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka/prod/dvh_sakstatistikk_behandling_v1_topic.yaml
  loggfeil:
    name: Send logg til slack ved feil
    runs-on: ubuntu-latest
    needs: [deploy-to-prod]
    steps:
      - name: Send logg til slack ved feil
        if: failure()
        run: |
          curl -X POST --data "{\"text\": \"Deploy av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
