name: Kjør StegServiceTest
on:
  push

env:
  IMAGE: ghcr.io/navikt/familie-ba-sak:${{ github.sha }}
jobs:
  build-jar-docker:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Test med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --no-transfer-progress package verify test -Dtest=StegServiceTest --settings .m2/maven-settings.xml --file pom.xml
